title: Hello Jekyll
description: >-
    Welcome to a test Jekyll site
baseurl: ""
url: ""
navbar-links:
  About: "about"
  Contact: "contact"

# Build settings
remote_theme: daattali/beautiful-jekyll@3.0.0 
